import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { ItineraryPlan } from "@/lib/types";
import { colors, dayColorStyle, pdfStyles as s } from "./styles";

/**
 * The base-14 Helvetica encoding react-pdf falls back to (no custom font
 * registered — see styles.ts) only reliably covers WinAnsi/Latin1. Confirmed
 * live: en-dash, em-dash, and the degree symbol all rendered as broken-glyph
 * "�" boxes in the generated PDF. Tips/quick_ref/activity text is
 * LLM-authored and can contain any of these (weather strings like "25-30°C",
 * curly quotes in phrases like "Fisherman's Wharf") — normalize to plain
 * ASCII equivalents everywhere backend-sourced text is rendered, not just in
 * this file's own hardcoded strings.
 */
function pdfSafe(text: string): string {
  return text
    .replace(/[–—]/g, "-") // en/em dash
    .replace(/[‘’]/g, "'") // curly single quotes
    .replace(/[“”]/g, '"') // curly double quotes
    .replace(/°/g, "deg ") // degree symbol
    .replace(/…/g, "...") // ellipsis
    .replace(/ /g, " "); // non-breaking space
}

function stripHtml(html: string): string {
  // Activity descriptions may contain <strong> highlights (per the LLM
  // prompt spec) — react-pdf's <Text> renders literal children, not HTML, so
  // the tags themselves would print as visible text if left in. No need for
  // DOMPurify here (this never touches a DOM/innerHTML), a plain tag strip is
  // enough since this is presentation-only, not being rendered as markup.
  return pdfSafe(html.replace(/<[^>]+>/g, ""));
}

function formatDateRange(startDate: string | null, days: number): string {
  if (!startDate) return "Flexible dates";
  const start = new Date(startDate);
  const end = new Date(start);
  end.setDate(start.getDate() + days - 1);
  const fmt = (d: Date) => d.toLocaleDateString("en-US", { day: "numeric", month: "short" });
  return `${fmt(start)} - ${fmt(end)}, ${end.getFullYear()}`;
}

function formatInr(n: number): string {
  return `Rs ${Math.round(n).toLocaleString("en-IN")}`;
}

function Footer({ destination }: { destination: string }) {
  return (
    <Text style={s.footer} fixed>
      {destination} itinerary - generated by TripNest
    </Text>
  );
}

export function ItineraryPdf({ plan, originCity }: { plan: ItineraryPlan; originCity: string }) {
  const content = plan.itinerary_plan;

  return (
    <Document title={`${plan.destination} itinerary`}>
      {/* Cover page */}
      <Page size="A4" style={s.coverPage}>
        <Text style={s.coverEyebrow}>{pdfSafe(content.weather_label)}</Text>
        <Text style={s.coverTitle}>
          {originCity} to {plan.destination}
        </Text>
        <Text style={s.coverTagline}>{pdfSafe(content.tagline)}</Text>
        <View style={s.coverMetaRow}>
          <Text style={s.coverMetaChip}>{formatDateRange(plan.travel_start_date, plan.days)}</Text>
          <Text style={s.coverMetaChip}>{plan.travelers} travelers</Text>
          <Text style={s.coverMetaChip}>{plan.days} days</Text>
        </View>
      </Page>

      {/* Day-by-day pages */}
      {content.days.map((day) => {
        const theme = dayColorStyle(day.number);
        return (
          <Page key={day.number} size="A4" style={s.page}>
            <View style={s.dayHeaderRow}>
              <View style={[s.dayBadge, { backgroundColor: theme.badgeBg, borderColor: theme.badgeBorder }]}>
                <Text style={[s.dayBadgeText, { color: theme.text }]}>{String(day.number).padStart(2, "0")}</Text>
              </View>
              <View>
                <Text style={[s.dayMeta, { color: theme.text }]}>
                  {pdfSafe(day.weekday)} - {pdfSafe(day.date)}
                </Text>
                <Text style={s.dayTitle}>{pdfSafe(day.title)}</Text>
                <Text style={s.daySubtitle}>{pdfSafe(day.subtitle)}</Text>
              </View>
            </View>

            {day.activities.map((act, i) => (
              <View key={i} style={s.activityCard} wrap={false}>
                <View style={s.activityRow}>
                  <View>
                    <Text style={[s.activityTime, { color: theme.text }]}>{pdfSafe(act.time)}</Text>
                    <Text style={[s.activityType, { color: theme.text }]}>{pdfSafe(act.type)}</Text>
                  </View>
                  <View style={s.activityBody}>
                    <Text style={s.activityTitle}>{pdfSafe(act.title)}</Text>
                    <Text style={s.activityDesc}>{stripHtml(act.description)}</Text>
                    {act.chips.length > 0 && (
                      <View style={s.chipsRow}>
                        {act.chips.map((chip, ci) => (
                          <Text key={ci} style={s.chip}>
                            {pdfSafe(chip)}
                          </Text>
                        ))}
                      </View>
                    )}
                  </View>
                </View>
              </View>
            ))}
            <Footer destination={plan.destination} />
          </Page>
        );
      })}

      {/* Budget */}
      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Estimated budget</Text>
        <Text style={s.sectionTitle}>Trip Economics</Text>
        <View style={s.grid2}>
          <BudgetCard label="Flights" sub="Round trip, per group" amount={plan.cost_summary.breakdown.flights} />
          <BudgetCard label="Accommodation" sub={pdfSafe(plan.hotel ?? "Hotel")} amount={plan.cost_summary.breakdown.hotel} />
          <BudgetCard label="Food & Dining" sub={`${plan.days} days of meals`} amount={plan.cost_summary.breakdown.food} />
          <BudgetCard label="Local Transport" sub="Cabs, transfers" amount={plan.cost_summary.breakdown.local_transport} />
          <BudgetCard label="Activities & Entries" sub="Experiences, tours" amount={plan.cost_summary.breakdown.activities} />
        </View>
        <View style={s.totalBanner}>
          <View>
            <Text style={s.totalAmount}>{formatInr(plan.cost_summary.total_inr)}</Text>
            <Text style={s.totalSub}>
              {plan.travelers} travelers - {plan.days} days
            </Text>
          </View>
          <View>
            <Text style={s.totalSub}>Per person</Text>
            <Text style={[s.totalAmount, { fontSize: 15, color: colors.primary }]}>{formatInr(plan.cost_summary.per_person_inr)}</Text>
          </View>
        </View>
        <Footer destination={plan.destination} />
      </Page>

      {/* Tips + Packing */}
      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Be prepared</Text>
        <Text style={s.sectionTitle}>{plan.destination} Travel Tips</Text>
        <View style={s.grid2}>
          {content.tips.slice(0, 6).map((tip, i) => (
            <View key={i} style={s.gridCard}>
              <Text style={s.gridCardLabel}>{pdfSafe(tip.title)}</Text>
              <Text style={s.gridCardSub}>{pdfSafe(tip.text)}</Text>
            </View>
          ))}
        </View>

        <Text style={[s.sectionEyebrow, { marginTop: 20 }]}>Don&apos;t forget</Text>
        <Text style={s.sectionTitle}>Packing Checklist</Text>
        <View style={s.grid2}>
          <PackingColumn heading="Essentials" items={content.packing.essentials} />
          <PackingColumn heading={pdfSafe(content.packing.weather_category)} items={content.packing.weather_items} />
          <PackingColumn heading="Clothing" items={content.packing.clothing} />
          <PackingColumn heading="Health & Misc" items={content.packing.health} />
        </View>
        <Footer destination={plan.destination} />
      </Page>

      {/* Quick reference */}
      <Page size="A4" style={s.page}>
        <Text style={s.sectionEyebrow}>Good to know</Text>
        <Text style={s.sectionTitle}>Quick Reference</Text>
        <View style={s.grid2}>
          <QuickRefItem label="Emergency" value={content.quick_ref.emergency} />
          <QuickRefItem label="Tourism Helpline" value={content.quick_ref.tourism_line} />
          <QuickRefItem label="Local Transport" value={content.quick_ref.local_cab} />
          <QuickRefItem label="Weather" value={content.quick_ref.weather} />
          <QuickRefItem label="Base Area" value={content.quick_ref.base_area} />
          <QuickRefItem label="Languages" value={content.quick_ref.languages} />
        </View>
        <Footer destination={plan.destination} />
      </Page>
    </Document>
  );
}

function BudgetCard({ label, sub, amount }: { label: string; sub: string; amount: number }) {
  return (
    <View style={s.gridCard}>
      <Text style={s.gridCardLabel}>{label}</Text>
      <Text style={s.gridCardSub}>{sub}</Text>
      <Text style={s.gridCardAmount}>{formatInr(amount)}</Text>
    </View>
  );
}

function PackingColumn({ heading, items }: { heading: string; items: string[] }) {
  return (
    <View style={{ width: "48%" }}>
      <Text style={[s.gridCardLabel, { marginBottom: 6 }]}>{heading}</Text>
      {items.map((item, i) => (
        <Text key={i} style={s.listItem}>
          - {pdfSafe(item)}
        </Text>
      ))}
    </View>
  );
}

function QuickRefItem({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ width: "48%", ...s.quickRefRow }}>
      <View>
        <Text style={s.quickRefLabel}>{label}</Text>
        <Text style={s.quickRefValue}>{pdfSafe(value)}</Text>
      </View>
    </View>
  );
}
